@BASE_URL=https://localhost:5001

### create reviewer
POST {{BASE_URL}}/api/user HTTP/1.1
Content-Type: application/json

{
  "userid": "e7d2d02c-417b-42a2-8f3f-434f9ed5c4dd",
  "fullname": "reviewer",
  "displayname":"ad employee"
}



### create seller
POST {{BASE_URL}}/api/user HTTP/1.1
Content-Type: application/json

{
  "userid": "ba23c309-4f62-4fca-8348-3ff186c62a72",
  "fullname": "seller",
  "displayname":"yuntech owner"
}

###

PUT {{BASE_URL}}/api/user/fullname HTTP/1.1
Content-Type: application/json

{
  "userid": "ba23c309-4f62-4fca-8348-3ff186c62a72",
  "fullname": "seller-update",
}

###

PUT {{BASE_URL}}/api/user/displayname HTTP/1.1
Content-Type: application/json

{
  "userid": "ba23c309-4f62-4fca-8348-3ff186c62a72",
  "displayname": "yuntech owner update",
}

###

PUT {{BASE_URL}}/api/user/photo HTTP/1.1
Content-Type: application/json

{
  "userid": "ba23c309-4f62-4fca-8348-3ff186c62a72",
  "photourl": "https://yuntech.edu.tw",
}