version: '2'

services: 

    mssql:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: marketplace-sqlserver
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "Heip5375"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Developer

    eventstore:
        image: eventstore/eventstore
        container_name: marketplace-eventstore
        ports: 
            - 2113:2113
            - 1113:1113
        environment: 
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_EXT_HTTP_PORT=2113
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true